export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const RECEIVE_JOBS = "RECEIVE_JOBS";
export const FETCH_JOBS = "FETCH_JOBS";
export const FILTERED_JOBS = "FILTERED_JOBS";

export const RECEIVE_SPOTLIGHTS = "RECEIVE_SPOTLIGHTS";
export const FETCH_SPOTLIGHTS = "FETCH_SPOTLIGHTS";

export const UNIQUE_ORGANIZATIONS = "UNIQUE_ORGANIZATIONS";
export const ADD_SELECTED_ORGANIZATIONS = "ADD_SELECTED_ORGANIZATIONS";

export const ADD_SELECTED_JOB_TYPES = "ADD_SELECTED_JOB_TYPES";
export const UNIQUE_JOB_TYPES = "UNIQUE_JOB_TYPES";

export const INCLUDE_JOB_BY_ORGANIZATIONS = "INCLUDE_JOB_BY_ORGANIZATIONS";
export const INCLUDE_JOB_BY_TYPES = "INCLUDE_JOB_BY_TYPES";
